<?php

$products = array(
    [1, "ADDIDAS NEW HAMMER SOLE GREY", "100.00", "p1.jpg"],
    [2, "NIKE NEW RUNNER FOR SPORTS PERSON", "120.00", "p2.jpg"],
    [3, "VANS SLIP-ON BLACK PANTER TENNIS", "70.00", "p3.jpg"],
    [4, "NEW BALANCE RUNNER TROPICAL", "85.00", "p4.jpg"],
    [5, "PUMA CASUAL TENNIS XX", "70.00", "p5.jpg"],
    [6, "UNDER ARMOUR WILD RUNNER", "100.00", "p6.jpg"],
    [7, "PUMA AIRFLOW CASUAL TENNIS", "65.00", "p7.jpg"],
    [8, "PUMA PINK PANTER SELECTION", "90.00", "p8.jpg"]
);

$cartItems = array();

$states = array(
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'District of Columbia',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming'
);