<?php

$products = array(
    [1, "ADDIDAS NEW HAMMER SOLE FOR SPORTS PERSON", "150.00", "p1.jpg"],
    [2, "ADDIDAS NEW HAMMER SOLE FOR SPORTS PERSON", "150.00", "p2.jpg"],
    [3, "ADDIDAS NEW HAMMER SOLE FOR SPORTS PERSON", "150.00", "p3.jpg"],
    [4, "ADDIDAS NEW HAMMER SOLE FOR SPORTS PERSON", "150.00", "p4.jpg"],
    [5, "ADDIDAS NEW HAMMER SOLE FOR SPORTS PERSON", "150.00", "p5.jpg"],
    [6, "ADDIDAS NEW HAMMER SOLE FOR SPORTS PERSON", "150.00", "p6.jpg"],
    [7, "ADDIDAS NEW HAMMER SOLE FOR SPORTS PERSON", "150.00", "p7.jpg"],
    [8, "ADDIDAS NEW HAMMER SOLE FOR SPORTS PERSON", "150.00", "p8.jpg"]
);

$cartItems = array();

$states = array(
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'District of Columbia',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming'
);